name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache SBT dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.sbt
          ~/.ivy2/cache
          target/repos
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Run tests
      run: sbt test
    
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ninja-name-generator-api:${{ github.sha }} .
    
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/ninja-name-generator-api:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to render.com
        run: |
          curl -X POST '${{ secrets.RENDER_DEPLOY_HOOK }}&imgURL=docker.io%2F${{ secrets.DOCKER_USERNAME }}%2Fninja-name-generator-api%3A${{ github.sha }}'